logging:
  level:
    root: INFO
    com:
      demo: DEBUG
      azure:
        core:
          amqp: ERROR
        messaging:
          eventhubs:
            PartitionBasedLoadBalancer: ERROR
            EventHubConsumerAsyncClient: ERROR
            EventHubClientBuilder: ERROR
            implementation: ERROR
    httpclient:
      wire: INFO
    org:
      apache:
        http: INFO
      springframework:
        web:
          client:
            RestTemplate: INFO
        integration:
          endpoint: ERROR

spring:
  application:
    name: azure-eventhubs
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
  cloud:
    azure:
      eventhub:
        connection-string: ${EVENTHUBS_CONNECTION}

        #Next configuration is needed for consumers:
        #checkpoint-storage-account: my-azure-storage-account
        #checkpoint-access-key: abcd-abcd-abcdt4g==
        #checkpoint-container: logging4
    stream:
      function:
        #Configuration for the producer and supplier
        #definition: supply;consume;
        #Configuration only for the producer:
        definition: supply
      bindings:
        #Configuration for the consumer
        #consume-in-0:
          #destination: logging4
          #group: $Default
        supply-out-0:
          destination: payloads
      #Configuration for the consumer
      #eventhub:
        #bindings:
          #consume-in-0:
            #consumer:
              #checkpoint-mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000

openapi:
  application-title: Credit Limit
  application-description: Credit Limit operations like history, update, etc
  application-version: 1.0
  contact:
    email: demo@demo.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html