logging:
  level:
    root: INFO
    com:
      democompany: DEBUG
    httpclient:
      wire: INFO
    org:
      apache:
        http: INFO
      springframework:
        web:
          client:
            RestTemplate: INFO

spring:
  application:
    name: azure-eventhubs
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
  cloud:
    azure:
      eventhub:
        connection-string: Endpoint=sb://myeventhub.servicebus.windows.net/;SharedAccessKeyName=basic;SharedAccessKey=mysharedkey;EntityPath=test
        checkpoint-storage-account: mystorageaccount
        checkpoint-access-key: mystorageaccount-key
    stream:
      function:
        definition: produce
      bindings:
        produce-out-0:
          destination: test

openapi:
  application-title: Credit Limit
  application-description: Credit Limit operations like history, update, etc
  application-version: 1.0
  contact:
    email: demo@demo.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

fiserv:
  url: ${FISERV_URL:https://fiserve.url.com}
  subscriptionKey: Subscription-Key
  subscriptionValue: ${SUBSCRIPTION_VALUE:aaaaaaa}
  user: demouser

  creditlimit:
    update: /maintenance/updateCreditLimit

